-- =============================================================================
-- Jeremiah Hiromi Effendi - Portfolio Database Schema for Supabase
-- Run this in your Supabase Project -> SQL Editor -> New Query -> Run
-- =============================================================================

-- 1. Create table for contact messages / client inquiries
CREATE TABLE IF NOT EXISTS messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  scope TEXT NOT NULL,
  message TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Enable Row Level Security (RLS) on messages
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;

-- 3. Policy: Allow any website visitor to submit contact inquiries
CREATE POLICY "Allow public insert into messages"
  ON messages
  FOR INSERT
  WITH CHECK (true);

-- 4. Policy: Only authenticated admin (you) can read received messages
CREATE POLICY "Allow authenticated read of messages"
  ON messages
  FOR SELECT
  TO authenticated
  USING (true);

-- =============================================================================
-- 5. (Optional) Dynamic Projects Table
-- If you want to manage portfolio projects dynamically from Supabase
-- =============================================================================
CREATE TABLE IF NOT EXISTS projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  tags TEXT[] NOT NULL DEFAULT '{}',
  objective TEXT NOT NULL,
  features TEXT[] NOT NULL DEFAULT '{}',
  image_label TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS on projects
ALTER TABLE projects ENABLE ROW LEVEL SECURITY;

-- Policy: Allow public read access on projects
CREATE POLICY "Allow public read access on projects"
  ON projects
  FOR SELECT
  USING (true);

-- Seed initial projects into projects table
INSERT INTO projects (id, title, description, tags, objective, features)
VALUES 
(
  1,
  'Personal Portfolio Website',
  'A responsive single-page personal portfolio designed to present personal information, skills, projects, and contact information in a professional digital format.',
  ARRAY['HTML5', 'CSS3', 'JavaScript'],
  'To build a clean, modern, and accessible single-page web portfolio showcasing academic background, digital capabilities, and practical projects.',
  ARRAY[
    'Fully responsive layout with sticky navigation and mobile slide-down drawer',
    'Dark / Light theme switcher with preference stored in localStorage',
    'Animated skill competency progress indicators triggered upon viewport entry',
    'Dynamic project detail modal dialog with keyboard ESC and backdrop dismiss',
    'Client-side validated contact inquiry form with clear user feedback'
  ]
),
(
  2,
  'Business Data Dashboard',
  'A conceptual dashboard designed to organize and visualize business-related information in a clear and accessible interface.',
  ARRAY['Data Visualization', 'UI Design', 'Business Analytics'],
  'To design and structure an analytical dashboard interface that consolidates core business KPIs, inventory metrics, and decision-support figures into clean visual modules.',
  ARRAY[
    'Modular KPI metric summary cards for quick managerial review',
    'Responsive data chart layouts and structured analytical components',
    'Filterable data views and segment status highlights',
    'Clear visual hierarchy optimized for fast scanning and reporting'
  ]
),
(
  3,
  'Business Landing Page',
  'A modern landing page concept designed to communicate a business value proposition and guide visitors toward a clear call to action.',
  ARRAY['HTML5', 'CSS3', 'Responsive Design'],
  'To create a high-converting digital landing page tailored for modern business ventures, emphasizing clarity, value proposition, and user experience.',
  ARRAY[
    'High-impact split-screen hero section communicating immediate value',
    'Product capability and customer trust endorsement blocks',
    'Optimized Call-to-Action pathways driving user engagement',
    'Mobile-first responsive styling ensuring consistency on all viewports'
  ]
)
ON CONFLICT (id) DO NOTHING;
